### ISSUE TITLE
How to pass string value inside the textarea of generating pdf from html?

### ISSUE THREAD

**Issue by suprithasraoa** [cesarvr/pdf-generator-example#2]
This is the code i am trying.Getting values from mysql database
But it doesnot work..  

 <textarea class="form-control" id="rawhtml" name="html">
<!DOCTYPE html>
<html>
 <head>
 <meta charset="utf-8">
 <title>my payment</title>
<style>
.rTableRow {
  	display: table-row;
}
.rTableCell {
  	display: table-cell;
  	padding: 1px 3px;
  	border: 1px solid #ccc;
}
</style>
 <script type="text/javascript">
$(document).ready(function() {
var url = "http://myurl/myphp.php";
 $.getJSON(url, function(result) {		
console.log(result);
 $.each(result, function(i, field) {		
 var Id = field.Id;
$("#sTableRow").append("<div class='rTableRow'><div class='rTableCell'>"+Id+"</div></div>");
 });
});
});
</script>
</head>
 <body>
<div class="rTable" id="sTableRow">
</div>
</body>
</html>
</textarea>

**Comment by cesarvr** [comment]
you can use [underscore template](http://underscorejs.org/#template) to compile the desired html template and then pass it to the plugin like this: 


<pre>    
//document ready
//generate divs 
var tmpl = _.template('"<%_.each(results, function(result){%> <div> <%=result%></div> <%})%>");

//cloud call
$.getJSON(url, function(result) { 
pdf.htmlToPDF({ data: tmpl({results: result}),
        }, successFn, failureFn);`
})
</pre>
